name: My build action requiring more space
on: push

jobs:
  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 4096
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout
        uses: actions/checkout@v2

      - name: build 
        run: |
          echo "Free space:"
          df -h
          
          git clone https://github.com/brave/brave-browser.git
          git clone --branch "v1.54.15" https://github.com/brave/brave-core.git brave-browser/src/brave
          cd brave-browser/src/brave
          npm install
          sed -i 's/\'--with_tags\', \'--with_branch_heads\', \'--upstream\'/\'--with_tags\', \'--with_branch_heads\', \'--upstream\', \'--no-history\'/' build/commands/scripts/sync.js
          npm run init
          ./install-build-deps.sh --no-prompt
          npm run build Release
